### ISSUE TITLE
Englischer Sourcecode

### ISSUE THREAD

**Issue by Dalanie** [Integreat/app-cross_platform#1]
Bitte Sourcecode + Kommentare nur auf Englisch, da die App u.U. auch von Non-Native Speakern weiterentwickelt wird.

(Man koennte drueber streiten ob dann nicht auch diese Tickets auf Englisch sein muessten ;) )

**Comment by Meash** [comment]
Tickets sind relativ kurzlebig, kann man dann ggf noch anpassen. Source
Code ist da langlebiger, den sollten wir auf alle Fälle direkt auf englisch
halten.

**Comment by Dalanie** [comment]
Hab es ins Wiki aufgenommen.
