### ISSUE TITLE
change language list shows languages from other blog

### ISSUE THREAD

**Issue by sven15** [Integreat/app-cross_platform#101]
when using the change language setting, the list ist shown from some previously selected city. For example regensburg had french and farsi available which are only available inaugsburg (previously had augsburg as location).
Maybe that is only a problem for regensburg. Not sure yet.

**Comment by sven15** [comment]
Maybe that is only a problem for regensburg. Not sure yet.

**Comment by BerndNK** [comment]
Alright I was able to reproduce the bug. Fix is on it's way
