### ISSUE TITLE
Translations for main menu required

### ISSUE THREAD

**Issue by svenseeberg** [Integreat/app-cross_platform#102]
The main menu / tabs is german after changing to another language.

**Comment by BerndNK** [comment]
Main menu (and all other system strings "search", "no results found" etc.) are only changed with the device OS setting. Currently however, the changes are only affected after restarting the app. I don't think it will be a valid use case to have the app change it's OS language on the fly?

**Comment by thimmy687** [comment]
Should we change this or can this issue be closed?

**Comment by thimmy687** [comment]
@svenseeberg and @BerndNK can we close this or is this still open and we discuss this on I8K?
