### ISSUE TITLE
app crash when changing language

### ISSUE THREAD

**Issue by sven15** [Integreat/app-cross_platform#103]
App crashes after clicking on another language. This language was not available for this city (see #101). However in most cases it simply opened an empty list instead of crashing.
![screenshot_20170420-124012](https://cloud.githubusercontent.com/assets/15197000/25227806/41d32c2c-25ca-11e7-9332-03bfa15968fa.png)
![screenshot_20170420-124020](https://cloud.githubusercontent.com/assets/15197000/25227807/41d4e4ae-25ca-11e7-87aa-467ffeec934c.png)
![screenshot_20170420-124024](https://cloud.githubusercontent.com/assets/15197000/25227802/41975bac-25ca-11e7-878f-e5d8ebc5c976.png)
![screenshot_20170420-124035](https://cloud.githubusercontent.com/assets/15197000/25227809/429863e8-25ca-11e7-8ec2-7c075a141ef2.png)
![screenshot_20170420-124042](https://cloud.githubusercontent.com/assets/15197000/25227803/41979572-25ca-11e7-8689-2d42af6afa76.png)
![screenshot_20170420-124049](https://cloud.githubusercontent.com/assets/15197000/25227804/4197b05c-25ca-11e7-9b50-68b14700395a.png)
![screenshot_20170420-124051](https://cloud.githubusercontent.com/assets/15197000/25227805/41a99394-25ca-11e7-81f7-6541bf324516.png)

**Comment by sven15** [comment]
Crahs report: https://owncloud.geeq.de/index.php/s/QmsvWuMikD2G7U9

**Comment by BerndNK** [comment]
I think this can be closed, as #101 is the real problem.  With #101 fixed, this error will never occur.
