### ISSUE TITLE
app crash when scrolling search result

### ISSUE THREAD

**Issue by sven15** [Integreat/app-cross_platform#104]
![screenshot_20170420-124549](https://cloud.githubusercontent.com/assets/15197000/25227787/32ed2230-25ca-11e7-962b-1a2340fb49a3.png)

**Comment by sven15** [comment]
https://owncloud.geeq.de/index.php/s/uB7iYi379JjrhkQ

**Comment by BerndNK** [comment]
Not easy to reproduce. We'll have to see if this error still occurs with the other fixes. This might also be a result of the bugs which appeared in the REST Api recently. (On Regensburg Arabic)

**Comment by BerndNK** [comment]
I was able to reproduce it. Fixed in bf77406
