### ISSUE TITLE
Secret API URL setting

### ISSUE THREAD

**Issue by svenseeberg** [Integreat/app-cross_platform#106]
Use the location search to set the API URL.
For example "api_url=https://domain.tld/rest/api/" or "api_url=reset" and hit enter.

This would be very helpful for debugging the CMS.

**Comment by thimmy687** [comment]
Hi @svenseeberg, kannst du etwas mehr ausführen, was du genau möchtest?

Geht das nicht auch mit [Postman](https://www.getpostman.com/) oder einem änlichen Tool?
