### ISSUE TITLE
Can't load the location augsburg

### ISSUE THREAD

**Issue by thimmy687** [Integreat/app-cross_platform#123]
if I select the location Augsburg the app doesn't load the languages page

**Comment by thimmy687** [comment]
@BerndNK has the suggestion it is a cms topic, because we can't load the json via API

**Comment by BerndNK** [comment]
It seems the REST Api has some overlapping URL's with the WebApp
Works (Regensburg): https://cms.integreat-app.de/regensburg/de/wp-json/extensions/v0/languages/wpml
Doesn't work (Augsburg): https://cms.integreat-app.de/augsburg/de/wp-json/extensions/v0/languages/wpml
Note that both URL's are almost the same, except that the location is changed

**Comment by sven15** [comment]
Daniel fixed it
