### ISSUE TITLE
Event List needs more margin

### ISSUE THREAD

**Issue by dkehne** [Integreat/app-cross_platform#131]
![photo_2017-05-15_11-14-32](https://cloud.githubusercontent.com/assets/4182469/26050672/c7c02ce2-395f-11e7-8ffd-a839d6afed94.jpg)

**Comment by thimmy687** [comment]
wo genau möchtest du denn mehr margin haben @dkehne?

**Comment by dkehne** [comment]
Margin of the Webview - equal to normal pages:

<WebView
            Margin="20,0,20,0"

**Comment by thimmy687** [comment]
done in PR EventPages
