### ISSUE TITLE
Windows-Phone Integration

### ISSUE THREAD

**Issue by Dalanie** [Integreat/app-cross_platform#14]
We need to integrate (great word) Windows-Phone and Windows-Phone-Test projects.

**Comment by rjuergen** [comment]
Windows 10 Universal App or Windows 8.1 Universal App?

Do we want to support Windows 8.1?

"The best way to be ready for Windows 10 is to build your Universal Windows app for Windows 8.1 and Windows Phone 8.1 now."- Microsoft
http://stackoverflow.com/questions/30317848/run-windows-10-universal-apps-on-windows-8-1

**Comment by Dalanie** [comment]
New is always better! :) Windows 10 ist doch auch sicher kompatibel mit
Windows 8.

Kann man des in Windows fürs Debugging direkt starten?

**Comment by rjuergen** [comment]
Ich suche gerade ob Windows 10 Universal Apps auch auf Windows 8 laufen. Find aber nicht so recht was. 
Auf dem stackoverflow link heißt es: "Windows 10 introduces several new APIs and concepts (such as API contracts) that are not available on Windows 8.1. An app that relies on such new APIs and concepts cannot run on Windows 8.1."
Find aber noch nichts ofizielles von microsoft.

**Comment by rjuergen** [comment]
Windows 10 Universal Apps laufen NICHT auf Windows 8.x Geräten.

official requirements
https://msdn.microsoft.com/en-us/library/dn975273.aspx

**Comment by Dalanie** [comment]
Naja können wir nicht zwei apps haben, 10 und 8?

**Comment by rjuergen** [comment]
Ja würde ich auch sagen.
Das WUP bei Windows 8.x ist leider wiederrum in Windows, WindowsPhone und Shared aufgeteilt. Bei WUP mit Windows 10 wird der gleiche Windows 10 core verwendet. Daher würde ich bei Windows 8.x nur die WindowsPhone variante implementieren.

Also ein "WindowsPhone8.x" und ein "Windows 10 Universal App" projekt. Einverstanden?

**Comment by Dalanie** [comment]
klingt gut, solange wir die bisherigen shared projects behalten koennen

**Comment by rjuergen** [comment]
Wenn die projekte Integreat.WP8 und Integreat.UWP passen erstell ich noch die Test projekte.

Problem WP8: schlechte unterstützung in sachen reflections. hoffe das bleibt das einzige problem
