### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by mschrimpf** [Integreat/app-cross_platform#15]
Anonymized User-Behaviour, used languages, crashes, ...

**Comment by Dalanie** [comment]
https://developer.xamarin.com/guides/insights/platform-features/

**Comment by Dalanie** [comment]
https://theconfuzedsourcecode.wordpress.com/2015/07/18/okay-finally-lets-add-google-analytics-to-xamarin-forms/ this one!

**Comment by dlangerenken** [comment]
@bjenik How far are we with this in iOS? Ready to go? (Haven't tried it out in Android yet...)

**Comment by bjenik** [comment]
I implemented it to close #52 (should be included in #60 see https://github.com/Integreat/app-cross_platform/blob/master/Integreat/Integreat.iOS/AnalyticsService.cs )
The actual analytics ID is still missing and I have not really tested if it works well (when enabling debug printout it seems to track events, but not sure if all of them)

**Comment by mschrimpf** [comment]
What's left to do for this issue? Do you need the analytics ID?

**Comment by BerndNK** [comment]
If I remember correctly, we decided to drop this feature for now.
