### ISSUE TITLE
Event content Bocholt

### ISSUE THREAD

**Issue by thimmy687** [Integreat/app-cross_platform#152]
Bocholt->English->first Event(Intercultural ...)

**Comment by dkehne** [comment]
Can you give a more detailed description of that issue?

**Comment by thimmy687** [comment]
Try to open Bocholt, in Language English, then go to event Page and open the first event.

something is wrong with the content, I believe this is a problem from the user self

@dkehne

**Comment by thimmy687** [comment]
closed because no app issue
