### ISSUE TITLE
Things that can't be realized using Xamarin.Forms 

### ISSUE THREAD

**Issue by Dalanie** [Integreat/app-cross_platform#16]
So far, the following *features* the android-app offers, cannot be realized using plain Xamarin.Forms:

- Image-Transformations: Converting images to a specific color is nothing Xamarin.Forms.ImageView offers or which can be done easily. Thus, we need to implement this feature for every single device (if desired.)
- Using Javascript inside of a WebView (maybe https://github.com/XLabs/Xamarin-Forms-Labs/wiki/HybridWebView might help, but Xamarin.Forms does not offer JavaScript support)
- Fancy loading/replacements of images during loading or in case of an error (same problem as converting images: more than just displaying images is not supported)
- ListView animations such as Remove, Add, Update are not supported (maybe https://github.com/XLabs/Xamarin-Forms-Labs/wiki/DynamicListView would help)
- tbc...

**Comment by Dalanie** [comment]
@FeuerwehrCloud  Benedikt, could you verify that there is no way to realize these things using Xamarin Forms?

**Comment by FeuerwehrCloud** [comment]
@Dalanie 

Transformations, Fancy loading and ListView-Animations - this functions need to be implemented using renderers on each platform - most of the functions may available as nuget-packages

WebView and Javascript are not working? I've used javascript (pdfjs - local stored, calendard - remote files) in my FeuerwehrCloud-App and they are working fine

**Comment by FeuerwehrCloud** [comment]
Transformations could be done creating our own imagesource, or by implementing a custom imageview that provides a transformation methode
