### ISSUE TITLE
App Crashes by clicking "Einstellungen" in Euskirchen Instance

### ISSUE THREAD

**Issue by Ponitac** [Integreat/app-cross_platform#161]
If you go to the Euskirchen Instance and click on "Einstellungen/Options/....." the App crashes and creates a Crash Report.
![crash_report_options_selected](https://cloud.githubusercontent.com/assets/15608678/26358160/f28ebbdc-3fd1-11e7-9c0e-5567d2eccd7d.png)

**Comment by thimmy687** [comment]
solved in #164
