### ISSUE TITLE
Crash when leaving the app by pressing the back button

### ISSUE THREAD

**Issue by maxammann** [Integreat/app-cross_platform#167]
# When does this happen?

Note: Just cleared the app cache and the exception is gone...

1. Open the app
2. You see the Augsburg page (selected preivously)
3. Press the back button on your device
4. Reopen the App (Splash screen appears again)
5. You see the following exception:
![screenshot_20170527-131514](https://cloud.githubusercontent.com/assets/905221/26549709/9ba63acc-447a-11e7-9823-894ba2d91278.png)

**Comment by thimmy687** [comment]
Hallo @maxammann welche Android Version und welches  Gerät verwendest du denn?

**Comment by thimmy687** [comment]
Ich denke, die exception fliegt, wenn der Navigation Stack leer ist...
Das passiert auch wenn man NavigateToRoot auf der Riot Seite ausführt

**Comment by BerndNK** [comment]
Failed to reproduce. Other updates might already have fixed this issue.
