### ISSUE TITLE
Crash if "Kontakt" in top bar is clicked

### ISSUE THREAD

**Issue by FritjofK** [Integreat/app-cross_platform#193]
*Please provide the following information if possible*

*System information:*
* Platform (Android or iOS): IOS
* Android or iOS version: 10.2.1 
* Device: iPhone 7

*App information* 
* App version: 2.0.98

*Bug information*
* Bug report
in the top bar, if I click on "Kontakt" the app crashes

* Expected behavior
Show the Disclaimer (Impressum) 

*additional screenshots are also helpful
well...it just crahes ;)

**Comment by thimmy687** [comment]
#192
