### ISSUE TITLE
Support more languages

### ISSUE THREAD

**Issue by thimmy687** [Integreat/app-cross_platform#197]
The App should also support the more language to reach a larger audience.

e.g. french

**Comment by BerndNK** [comment]
This is more a question for management and less for the app development team. As soon as we have more strings to build into the app, an issue may be created to do so. 
Sheet for our available translations: https://docs.google.com/spreadsheets/d/1vnmt4CpwIM49VC6fpywPTfTMkG2XK2btRNf0VOPOKrE
