### ISSUE TITLE
Change all Icons to flaticon

### ISSUE THREAD

**Issue by thimmy687** [Integreat/app-cross_platform#214]
We need to change all icons to Flaticon to avoid possible license violations

**Comment by BerndNK** [comment]
Some of the icons were created by me though. Can you specify exactly which icons have the be changed?

**Comment by BerndNK** [comment]
Specifically only
* calendar159.png
* extras100.png
* home150.png
* settings100.png
(and the equivalent \@2, \@3 sizes for iOS) 
need to be changed. These are from icons8.com
(Note that these are scattered throughout the solution structure: Integreat.iOS/Resources, Integreat.UWP/ and within various folders in Integreat.Droid/Resources)

All other icons are either
* created by us, or
* created by our partners (C4R, Lehrstellenradar)
and therefore won't violate any license agreements.

**Comment by thimmy687** [comment]
I saw it is also allowed to use the material icons without licence issues, so that I would recommend to use this
