### ISSUE TITLE
Navigation.PopToRootAsync can throw unhandled exception if fired on root 

### ISSUE THREAD

**Issue by thimmy687** [Integreat/app-cross_platform#217]

**Comment by BerndNK** [comment]
Not really a bug, but something the developer has to work with, no?

**Comment by thimmy687** [comment]
don't trust the developers ...:D

we should catch this...

**Comment by BerndNK** [comment]
This function is designed to be called when the current page is not the root page. Popping to root doesn't make sense when the current page already *is* root. Therefore throwing an exception makes sense. 
"don't trust the developers ...:D" 
For this reason exceptions exist, so the developer gets a loud alert signaling that what he did was wrong. I don't agree with this being an issue.
