### ISSUE TITLE
Meta data for html content pages 

### ISSUE THREAD

**Issue by thimmy687** [Integreat/app-cross_platform#221]
We should add some meta data like permalink or title which help to describe problems or enhancements

**Comment by BerndNK** [comment]
You mean in on the content pages themselves? Or hidden like in the "..."-button with a "copy permalink" or "show metadata" option?

**Comment by thimmy687** [comment]
Yes in content themselve

**Comment by thimmy687** [comment]
Yes I mean on the content themselve
