### ISSUE TITLE
Change Language within a Page

### ISSUE THREAD

**Issue by dlangerenken** [Integreat/app-cross_platform#23]
This feature is not yet implemented. We only need to check whether or not AvailableLanguage exists in a page

**Comment by BerndNK** [comment]
The List of AvailableLanguage's wasn't loading properly. There were some issues with foreign keys and all together I didn't manage to get the ManyToOne attribute to properly load the models. In the end I removed the Language and Page properties from the AvailableLanguage model and just left it with the page and language id. I also created a method in the MainPageViewModel which gets called when the user requests a language change within a page. It then switches the entire language to this very language and navigates back to the page (now with the new language).
Originally I was planning to just show the page in another language, however (as far as I know) there is no way to load a single page individually from our server, so I sticked with this solution instead.
