### ISSUE TITLE
Offline Availabity not fully supported - crashes after language change

### ISSUE THREAD

**Issue by dkehne** [Integreat/app-cross_platform#265]
*System information:*
Android and iOS
Integreat 2.14

The offline function of the app leads to crash in the following use case:

I suppose that opening the app in a specific location with the language German leads to an offline caching of the language German in this location. Repeating the process for another language English in the same location should also store this language on the users smartphone. So German and English should now be stored on the phone. Changing to flight mode now or disconnecting the smartphone from internet access and change the language to the former stored language (German) the app crashes - on both platforms Android and iOS. Also it's not possible to start the app again - until flight mode is deactivated.

**Comment by BerndNK** [comment]
The crash issue has been resolved.

However I have two notes on this issue:
* We only cache one language at a time
* When the user switches languages or locations, the cache gets cleared. (This however will be removed, since we have the "clear cache" button in the settings now)
