### ISSUE TITLE
Translate Resources

### ISSUE THREAD

**Issue by dlangerenken** [Integreat/app-cross_platform#28]
A few parts of the app contain hardcoded strings. These need to be translated to the 4-5 common languages for asylum seekers and accessed via resources

**Comment by Meash** [comment]
depends on Integreat/cms#340

**Comment by dkehne** [comment]
We are working on it. Languages German, English and Arabic are most important.

Strings can be found here:
https://docs.google.com/spreadsheets/d/1vnmt4CpwIM49VC6fpywPTfTMkG2XK2btRNf0VOPOKrE/edit#gid=0
