### ISSUE TITLE
Menu is in MainPage missing

### ISSUE THREAD

**Issue by thimmy687** [Integreat/app-cross_platform#301]
The change Location/Language and Settings ist erst sichtbar, wenn man in eine unter seite navigiert

**Comment by Simple-codinger** [comment]
The secondary toolbar should have the same look like android. (Three dots on the top)

**Comment by Simple-codinger** [comment]
![r1vai](https://user-images.githubusercontent.com/10844097/32978523-182e7fa4-cc44-11e7-8d68-a4bc0206cf46.png)

Or maybe like this

**Comment by Simple-codinger** [comment]
#392
