### ISSUE TITLE
Remove the C4R support and code

### ISSUE THREAD

**Issue by dkehne** [Integreat/app-cross_platform#326]
The careers4refugees extra was developed earlier this year but will not be supported anymore by now. The CMS ticket is already opended. It should be removed in the app as well

**Comment by thimmy687** [comment]
At this point I would recommend to change the extras feature to a more generic solution with an API change...

The api should deliver all integrations as array with all information

@svenseeberg

**Comment by thimmy687** [comment]
It is enough to disable this feature on our cms system.

We will remove this "hardcoded" feature during the changes for the next API
