### ISSUE TITLE
Update in Arabic

### ISSUE THREAD

**Issue by Dalanie** [Integreat/app-cross_platform#34]
It doesnt seem to work at all. Not showing arabic items/texts/anything

**Comment by Meash** [comment]
In terms of RTL support: 

> update your AndroidManifest.xml source to use the `android:supportsRtl="true"`
(from https://forums.xamarin.com/discussion/5600/persian-arabic-layout)

**Comment by Dalanie** [comment]
available languages seems to work.. weird problem

**Comment by Dalanie** [comment]
new version seem to have fixed it
