### ISSUE TITLE
Change Serlo ABC URL

### ISSUE THREAD

**Issue by dkehne** [Integreat/app-cross_platform#352]
Serlo ABC has released it's new app. During they have no webapp atm, we should nevertheless change our Serlo link to https://abc-app.serlo.org/ when the extra-button is triggered. 

The link directs to the play or app store. The current link is directing to the demo version, which is not only buggy but also only 5% of the functionality of the new app.

**Comment by thimmy687** [comment]
Related to this, we should move the URL to the CMS system so it is not hard coded in our app

**Comment by dkehne** [comment]
I agree on that in mid-term. But currently hard-coded is the easist temporary solution and the cms-solution would currently make a lot of effort in the CMS (because we have to activate it in every city and due to the proxy-issues we have to refresh every instance 3 times before the change becomes active). That's about 4-5 hours of work. And if there is again a change in the URL, again 4-5 hours ...
