### ISSUE TITLE
HTML in description 

### ISSUE THREAD

**Issue by mschrimpf** [Integreat/app-cross_platform#38]
I think I saw this during our presentation: if the description contains HTML content (such as <em>text</em>, it is not properly rendered but instead the HTML source is displayed.

**Comment by Dalanie** [comment]
we need to write a custom renderer... tried to start with imagecellrenderer, but failed so far

**Comment by dlangerenken** [comment]
Should we really implement this (lots of work) or can we make sure that the description only contains non-html text? (only shown in 2nd layer of pages and 1st layer of events)

**Comment by mschrimpf** [comment]
I guess if there's no easy way to do this, we could just remove all <tags> before displaying them in the app?

**Comment by thimmy687** [comment]
@BerndNK is this still a problem?

**Comment by thimmy687** [comment]
no response... -> closed
