### ISSUE TITLE
Link to play store not working

### ISSUE THREAD

**Issue by Simple-codinger** [Integreat/app-cross_platform#398]
If you click on Serlo-ABC the link to the Play Store is not working.

**Comment by thimmy687** [comment]
Is this still open @Simple-codinger ??

I tested it at the instance Bocholt, there it works fine.

or do you have some other not working example?

**Comment by thimmy687** [comment]
I guess we can use this way to solve this issue.
https://montemagno.com/opening-app-store-for-review-on-ios-and-android/

But generally SerloABC is only available for Android, so maybe we can switch generally to https://de.serlo.org/abc (or only for iOS)

**Comment by Simple-codinger** [comment]
We will remove the Serlo Extra anyway
