### ISSUE TITLE
Move drawables to mipmap

### ISSUE THREAD

**Issue by mschrimpf** [Integreat/app-cross_platform#40]
According to http://developer.android.com/guide/practices/screens_support.html:

> Note: **Place all your launcher icons in the res/mipmap-[density]/ folders, rather than the res/drawable-[density]/ folders**. The Android system retains the resources in these density-specific folders, such as mipmap-xxxhdpi, regardless of the screen resolution of the device where your app is installed. This behavior allows launcher apps to pick the best resolution icon for your app to display on the home screen. For more information about using the mipmap folders, see Managing Projects Overview.

**Comment by Dalanie** [comment]
yes. thats how android does it since a year - we dont have these folders yet ;)

**Comment by thimmy687** [comment]
#187
