### ISSUE TITLE
Feedback Funktionalität

### ISSUE THREAD

**Issue by thimmy687** [Integreat/app-cross_platform#414]
# Welche Informationen Fehlen aktuell

* Wofür soll das Feedback sein?
  * App-Funktionalitäten?
  * Page Content? 
* Wo soll es angezeigt werden?
  * genaue Position in der App (wsl unten)
* Wie soll das aussehen

Bitte Fragen überdenken, Mockup erstellen und hier verlinken

Vielleicht auch entsprechende WebApp Tickets hier hinterlegen (Link) um die Entwicklung synchron zu halten

**Comment by Simple-codinger** [comment]
https://fontawesome.com/icons/smile?style=regular
https://fontawesome.com/icons/frown?style=regular
