### ISSUE TITLE
Update content via mobile internet or WLAN

### ISSUE THREAD

**Issue by dkehne** [Integreat/app-cross_platform#42]
Does it make sense to have a user-controled functionality to decide wether content should be only synchronized via WLAN only or also with mobile data connection?

This is a feedback from Kissing, asking for this config parameter.

**Comment by Dalanie** [comment]
Would be easy to implement. Might be useful.  What about the first initial
loading, should it use this parameter as well?

**Comment by Dalanie** [comment]
Or do we set it to WiFi / mobile data by default and only after the initial
loading they can change that parameter?

**Comment by dkehne** [comment]
i would suggest to have it only in the settings. default: wifi + mobile data, and you can switch it to "wifi only".
