### ISSUE TITLE
Implement FCM push messages

### ISSUE THREAD

**Issue by mschrimpf** [Integreat/app-cross_platform#43]
Assuming push messages are not yet implemented, implement them ;)

Edit: This will happen through implementing FCM. The Firebase account is within the Keepass file. Before this issue may be implemented, #105 is required to be completed.

**Comment by svenseeberg** [comment]
@Simple-codinger I guess we can close this issue?

**Comment by svenseeberg** [comment]
It seems that there are some issues with FCM messages:
1) (Not all) iOS devices are not receiving messages.
2) Android devices get the messages show the messages twice. It seems that the CMS is sending the message only once.

**Comment by svenseeberg** [comment]
Feature implemented.
