### ISSUE TITLE
Implement new UI design

### ISSUE THREAD

**Issue by sven15** [Integreat/app-cross_platform#44]
Use the following images as a style reference for the new design.

![2 submenu_everyday life](https://cloud.githubusercontent.com/assets/15197000/13540519/5d62748c-e257-11e5-8e78-d9b46658cec5.png)
![3 detail view entry](https://cloud.githubusercontent.com/assets/15197000/13540520/5d6426ce-e257-11e5-9456-6973f27e89bc.png)
![1 main menu](https://cloud.githubusercontent.com/assets/15197000/13540521/5d66c37a-e257-11e5-8fc4-34fa582411ee.png)

**Comment by Dalanie** [comment]
These images show a hierarchy of layers that should be displayed within the app: The main menu should be the starting point (maybe we don't need to have a navigation drawer after all). If clicked on a 'category'/card it will open a list with entries of this type. If clicked on one of the entries, the detailed view of this entry is shown.

**Comment by dlangerenken** [comment]
implemented a card view
