### ISSUE TITLE
Can't load Raumfrei-Extra

### ISSUE THREAD

**Issue by Simple-codinger** [Integreat/app-cross_platform#442]
The offers are not shown in the "Raumfrei"-Extra. It seems that the Xamarin-Android Http-Client causes this issue.

**Comment by Simple-codinger** [comment]
We use modernhttpclient package for better Http-Client performance. Unfortunately the package is pretty much dead now, and it also doesn't support the latest Ok-Http as well as NSUrl features. So maybe we can find an alternative?

**Comment by svenseeberg** [comment]
This is an issue with the Raumfrei back end.
