### ISSUE TITLE
Character entities are not replaced by character in pages list

### ISSUE THREAD

**Issue by dkehne** [Integreat/app-cross_platform#443]
I have found some characters, which are not displayed correctly. I found it in Herne under "Events".
![photo_2019-01-14_14-42-28](https://user-images.githubusercontent.com/4182469/51116164-a1837f80-180a-11e9-9dc8-5a891821bc7f.jpg)

**Comment by svenseeberg** [comment]
@maxammann @timoludwig @Schedulaar: Vince and I are thinking about solving this in the REST API by replacing the entity codes with the correct UTF-8 characters. The list view in the Xamarin app is not using HTML widgets so we need to replace the characters somewhere. Does anybody see a problem with replacing the characters?

**Comment by maxammann** [comment]
Which fields in the page model would be affected?

**Comment by timoludwig** [comment]
`excerpt`, `content` and in special cases the `title`

**Comment by maxammann** [comment]
https://github.com/Integreat/integreat-webapp/blob/0a468743ab6148c7f1a0c28142cab14187164624/src/modules/endpoint/endpoints/events.js#L49

This is our solution in the webapp for this problem.

**Comment by maxammann** [comment]
Changing it should not break the webapp. But it may increase the already long API response time

**Comment by maxammann** [comment]
:+1: @svenseeberg we should specify this for django

**Comment by Simple-codinger** [comment]
Should be fixed: https://github.com/Integreat/app-cross_platform/commit/68a004b15a99b68d2f28877585ef9dd0b5653a06
