### ISSUE TITLE
PDFs cannot be opened on Android 

### ISSUE THREAD

**Issue by dkehne** [Integreat/app-cross_platform#449]
Linked PDFs do not open on Android phones. Example:

https://integreat.app/testumgebung/de/test/

The URL of the PDF is https://cms.integreat-app.de/testumgebung/wp-content/uploads/sites/154/2019/02/lorem_ipsum.pdf

**Comment by svenseeberg** [comment]
This seems to be a bug with Xamarin and could potentially be resolved by upgrading to Xamarin 4.0.0. The release will be in a couple of weeks.
