### ISSUE TITLE
Ehrenamts-Checkbox (für Push-News)

### ISSUE THREAD

**Issue by dkehne** [Integreat/app-cross_platform#45]
Ich habe eine gar nicht so schlechte Idee in Dormagen reinbekommen. Wenn man die App das erste Mal startet und die deutsche Sprache wählt bekommt man

a) evtl ein Popup á la "Wenn Sie Ehrenamtlicher Helfer sind setzen Sie bitte den Haken unter Menü -> Helfernachrichten"
b) Pushnachrichten im CMS können auch über eine Checkbox nur an Helfer mit der aktiven App für die Instanz XY geschickt werden.

So wird die App auch von Helfern als "1-seitiges" Kommunikationsmittel verwendet und wir gewinnen die Helferkreise als zusätzliche Multiplikatoren. Außerdem nutzen sowohl Helfer als auch Geflüchtete die gleiche App ohne dass wir aufdringlich am Anfang nach "Bist du Flüchtling oder Bürger" fragen, was ich niemals machen würde...

**Comment by Meash** [comment]
Finde eine Ausweitung der Nutzergruppe zwar gut, finde aber dass wir das vorher tiefer diskutieren sollten, was genau das bedeutet.
Insofern würde ich das Feature erstmal hinten anstellen.

**Comment by dlangerenken** [comment]
@dkehne  @mschrimpf  Ist das hier noch aktuell?

**Comment by dkehne** [comment]
Ja ist noch aktuell, aber ist quasi eine Erweiterung der Push-Nachrichten. Bauen darauf auf...

**Comment by dkehne** [comment]
i will implement this.

**Comment by BerndNK** [comment]
Updates on your assignment on this @dkehne ? Should I take over this issue?

**Comment by dkehne** [comment]
You take it @BerndNK  Thanks!

Is the normal implementation of the push news already live or is there a time schedule for that? @svenseeberg

**Comment by svenseeberg** [comment]
The CMS is prepared for this feature.

**Comment by svenseeberg** [comment]
Duplicate of #419
