### ISSUE TITLE
Store PDFs offline

### ISSUE THREAD

**Issue by mschrimpf** [Integreat/app-cross_platform#47]
Cache PDFs on the phone where the links direct to our domain.
See Integreat/app-android#123

**Comment by sven15** [comment]
As some cities are using this we should provide this feature with the initial release.

**Comment by BerndNK** [comment]
Implemented in d7c8334e94d0f4755dd9ed95effa4f607f217816
However, all pdf's which are on our server (starting with https://www.integrations-mediathek.de) cannot be cached, as the HttpClient (framework we use to load data from websites) requires a valid certificate. Example: https://www.integrations-mediathek.de/wp-content/uploads/2016/05/test.de-Mobiltelefonieren-in-Dutschland_deutsch.pdf
This is only a temporary effect, as we're currently working on to get the verification fixed.
