### ISSUE TITLE
iOS version not showing all events

### ISSUE THREAD

**Issue by svenseeberg** [Integreat/app-cross_platform#480]
In Ludwigsburg there are currently 2 events, but only one of them is appearing in the iOS app. On Android, both events appear.

![image](https://user-images.githubusercontent.com/15197000/64767342-cec63000-d547-11e9-849f-fc79e9c7a783.png)
![image](https://user-images.githubusercontent.com/15197000/64767363-d71e6b00-d547-11e9-8951-9d45bddf8d8e.png)
![image](https://user-images.githubusercontent.com/15197000/64767390-e9000e00-d547-11e9-926a-c889f314690b.png)

**Comment by dkehne** [comment]
cannot be reproduced anymore....
