### ISSUE TITLE
Font Size of Titles on 2nd and 3rd level differ on Android in Munich

### ISSUE THREAD

**Issue by FritjofK** [Integreat/app-cross_platform#481]
**PLEASE PROVIDE AN EXAMPLE**
See Screenshots from Munich on Android. 
Titles differ in font sizes for no apparent reason

**To further speed up development provide:**
* Android
* 8.0.0
* Samsung A3

**Screenshots are very helpful!**
![Screenshot_20191022-141135-576x1024](https://user-images.githubusercontent.com/16462172/67310393-f5d83000-f4fd-11e9-8cc1-e8cc6e7acc6d.jpg)
![Screenshot_20191022-141125-576x1024](https://user-images.githubusercontent.com/16462172/67310394-f5d83000-f4fd-11e9-840a-93af38681a5a.jpg)

Got some more Screenshots as examples if required.

**Comment by maxammann** [comment]
This is not reproducible for me on Android 9.0.

**Comment by maxammann** [comment]
![bs_realdroid_Mobile_Samsung Galaxy S9-8 0-1440x2960](https://user-images.githubusercontent.com/905221/67585315-8ce7f680-f74f-11e9-8469-d1a07e224bf4.jpg)

Thats how it looks on an S9 running Android 8

**Comment by maxammann** [comment]
![bs_realdroid_Mobile_Google Pixel-8 0-1080x1920](https://user-images.githubusercontent.com/905221/67585448-d33d5580-f74f-11e9-900d-67a1340ccddc.jpg)


Google Pixel Android 8

**Comment by vincentgierisch** [comment]
Galaxy S9 with Android 8

![bs_realdroid_Mobile_Samsung Galaxy S9-8 0-1440x2960](https://user-images.githubusercontent.com/10844097/67585535-0384f400-f750-11e9-97be-952869a4b1e2.jpg)

**Comment by maxammann** [comment]
![bs_realdroid_Mobile_Samsung Galaxy A8-7 1-1080x2220](https://user-images.githubusercontent.com/905221/67585623-36c78300-f750-11e9-9e0a-f1c487db4ef3.jpg)

Galaxy A8 Android 7

**Comment by maxammann** [comment]
![bs_realdroid_Mobile_Samsung Galaxy S9-8 0-1440x2960(1)](https://user-images.githubusercontent.com/905221/67586268-88bcd880-f751-11e9-9611-2e3cd9d972fb.jpg)

S9 with Android 8

**Comment by maxammann** [comment]
So it seems like it only happens for some devices on specific versions sometimes.

I suggest to close this issue and reopen it if it comes up again.

**Comment by svenseeberg** [comment]
Agreed.
