### ISSUE TITLE
Redirecting within the app

### ISSUE THREAD

**Issue by dlangerenken** [Integreat/app-cross_platform#49]
The backend now delivers the urls of pages along with the page which allows us to redirect within the app  instead of opening a url in a browser. We need to write an interceptor for the webview which takes the url, checks with the database if the url exists and opens the page accordingly

**Comment by dlangerenken** [comment]
@bjenik How easy is it to intercept clicks in a webview in iOS?

**Comment by bjenik** [comment]
For iOS there is https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIWebViewDelegate_Protocol/index.html#//apple_ref/occ/intfm/UIWebViewDelegate/webView:shouldStartLoadWithRequest:navigationType: which seems to be available in Xamarin: http://stackoverflow.com/questions/5406223/equivalent-of-the-uiwebview-selector-webviewshouldstartloadwithrequestnavigati to intercept an URL change of a webview - if you actually want to have clicks I believe doing it in js would be best

**Comment by sven15** [comment]
Whats the difference to #57?

**Comment by dlangerenken** [comment]
This ticket can only be done if #57 is implemented as we need a custom renderer for this.

**Comment by sven15** [comment]
This is still a problem that should be solved before release.

**Comment by sven15** [comment]
Couldn't we just parse all links when fetching updates from the api and replace them with JS calls or something that can be handled by the app?

**Comment by BerndNK** [comment]
The Navigating event is implemented in the commit b12aa57, however the functionality is impossible to achieve with the data we currently receive from the Server.

It's literally impossible to get the page for a given URL, as the URL is not the same as the page's title. Example: https://cms.integreat-app.de/regensburg/de/leben-in-regensburg/freizeit-religion-kultur/ggf-beratungansprechpartner
is the URL. The page's title however is "Wer kann mir helfen? Beratung"
Also the URL's has spaces as "-". Some titles however have a "-" in it's name. Example: https://cms.integreat-app.de/regensburg/de/leben-in-regensburg-2/freizeit-religion-kultur/erklaerungsblock/
There is no way of knowing, when a "-" in the url is an actual "-" or just a parsed space.

One way to solve this, is to send the web URL of a page as attribute. This way we could easily search for the page inside the app.

**Comment by sven15** [comment]
But the URL for each page is available in http://cms.integreat-app.de/regensburg/en/wp-json/extensions/v0/modified_content/pages?since=2017-05-10T11:30:00Z
You basically need to iterate through all page URLs and compare them. I agree that calculating the URLs is not possible.

Algorithm:
* Does link begin with `cms.integreat-app.de`
* Loop through all stored pages and compare page URLs with link URL

**Comment by BerndNK** [comment]
Right. My bad, I looked at the JSON which the device currently saves instead of the one we receive from the server. I forgot that properties which are not within our model do get ignored. 
Then I would have seen the permalinks.
