### ISSUE TITLE
Zeilenumbruch soll implementiert werden

### ISSUE THREAD

**Issue by dkehne** [Integreat/app-cross_platform#50]
Absatz (Enter) und Zeilenumbruch (Shift-Enter) soll auch in der App dargestellt werden.

**Comment by dlangerenken** [comment]
If this problem still exists, we would need to write a custom-webview-renderer.

**Comment by dlangerenken** [comment]
kein problem von der app - muss im backend geschehen

**Comment by mschrimpf** [comment]
Ist das related to Integreat/cms#413?

**Comment by dlangerenken** [comment]
Glaube nicht - auf jeden Fall hat es aber in Xamarin nix zu suchen ;) Das muesst ihr im HTML anpassen :) 
@dkehne Bitte kommentiere hier oder direkt in CMS-git

**Comment by dkehne** [comment]
Ich weiß nicht ob das mit 413 zusammenhängt. Es ging darum, dass Shift+Enter und Enter zwar in der Preview richtig dargestellt wurden, dann aber in der App nicht. Eventuell muss das aus Xamarin in Richtung CMS...

**Comment by sven15** [comment]
Hängt zusammen. Bisher werden Shift+Enter zu \<p\> ersetzt und damit Absatz. Mit dem neuen commit würde ein \\n zu einem \<br>
