### ISSUE TITLE
DependencyResolutionException When App Starts

### ISSUE THREAD

**Issue by ChrisSchneider** [Integreat/app-cross_platform#53]
When the app is launched a Autofac.Core.DependencyResolutionException is thrown

An exception was thrown while invoking the constructor 'Void .ctor(IAnalyticsService, LocationsLoader, Func`2, INavigator)' on type 'LocationsViewModel'. ---> An exception was thrown while invoking the constructor 'Void .ctor()' on type 'LocationsPage'. ---> Could not load file or assembly 'Integreat.Droid' or one of its dependencies (See inner exception for details.) (See inner exception for details.)

ViewFactory.cs:39

**Comment by Dalanie** [comment]
why is ios throwing a droid-related exception?
