### ISSUE TITLE
WebView - Custom behavior

### ISSUE THREAD

**Issue by dlangerenken** [Integreat/app-cross_platform#57]
We need a WebView Custom behaviour:
- we need to intercept the 'OnLinkClick' Method to redirect to other pages within the app

**Comment by sven15** [comment]
I was reading "custom renderer" like "we need to code our own browser" :D

**Comment by sven15** [comment]
Whats the difference to #49?

**Comment by dlangerenken** [comment]
This ticket includes several changes such as: 'Inject CSS-Code as we have in Android'. So 49 would be a subticket for this.

If we have custom-renderer, we can build up on these and implement 49.

So for now, a custom renderer should do exactly what the xamarin forms webview is doing ;).

**Comment by dlangerenken** [comment]
Another issue would be: If clicked on a pdf - we should look whether or not the pdf is on the phone and load it from there, ..

**Comment by BerndNK** [comment]
Now with pdf storage implemented in a different way, this issue is a complete duplicate to #49
