### ISSUE TITLE
Determine iOS release roadmap

### ISSUE THREAD

**Issue by sven15** [Integreat/app-cross_platform#64]
Some cities are desperately waiting for the iOS release. We need to define the needed features and to find out how soon we can implement them.

**Comment by dlangerenken** [comment]
@bjenik Can't we release the version as it is?

**Comment by bjenik** [comment]
The issue with the side menu not auto closing on selection needs to be fixed - other than that we should be ok.

In addition, https://blog.xamarin.com/easily-automate-your-xamarin-forms-apps/ would be nice - 5 screenshots times 6 (screen sizes) times # languages we want to ship is not something I would suggest doing by hand.

**Comment by BerndNK** [comment]
Okay, I'll created an issue for it. Issue #66 
I'm looking into it

**Comment by dlangerenken** [comment]
I think changing language within a page is not working yet and we should
remove the icon for now. It still shows up in the navigation  right?

**Comment by dlangerenken** [comment]
It is working in the main-menu but not in the page itself. And as far as I remember (dont have the app on my phone right now) - the language change icon is in the menu but only displaying the same language all the time

**Comment by dlangerenken** [comment]
So either implement #23  or get rid of it for the first release ;)
