### ISSUE TITLE
Scaling of 6+2 Categories

### ISSUE THREAD

**Issue by FritjofK** [Integreat/app-cross_platform#74]
![kategorie wird nicht ubersetzt](https://cloud.githubusercontent.com/assets/16462172/23723161/6fc959a6-0448-11e7-97e3-512040a74482.PNG)

Even 6 categories are not shown on one page (one must scroll). 
We have sold to cities that 8 categories can be shown on first site without scrolling

**Comment by dkehne** [comment]
It really depens on the screensize. We will deliver a default sizing. A sizing even if there are 6 categories might be necessary.

**Comment by dkehne** [comment]
Closed because we have adjusted it as far as possible.
