### ISSUE TITLE
When selecting language, add the name of the city at the top in addition to the picture

### ISSUE THREAD

**Issue by FritjofK** [Integreat/app-cross_platform#80]
Would make a better screenshot ;) 
Should be discussed first.

**Comment by BerndNK** [comment]
I added a label in 499d897a7f7c61e4cdfaa8a0bcedc0e2d0a81826
Open for discussion, otherwise this issue can be closed?
![screenshot_1490087710](https://cloud.githubusercontent.com/assets/7613199/24140171/4a887e02-0e1f-11e7-95ea-852e0a7ab86a.png)

**Comment by dkehne** [comment]
done.
