### ISSUE TITLE
Suchfunktion verfeinern & Suche scheint im Arabischen nicht zu funktionieren

### ISSUE THREAD

**Issue by FritjofK** [Integreat/app-cross_platform#83]
- Suchergebnisse zu klein
**- Nur Überschriften anzeigen?**
- Back-Icon oben Links ist weiß, also nicht sichtbar (siehe rotes Rechteck)
- Such-Funktion im Arabischen funktioniert nicht
![suche](https://cloud.githubusercontent.com/assets/16462172/24321961/42d1980e-115a-11e7-8738-13bacf0443b0.jpg)

**Comment by FritjofK** [comment]
One cannot click on the search results to get to the pages

**Comment by BerndNK** [comment]
Seems to be working fine in the current revision. 
![workingarabic](https://cloud.githubusercontent.com/assets/7613199/25133883/55c8adec-244e-11e7-98cc-4d6938c6a95d.PNG)
