### ISSUE TITLE
Special characters displayed as NCR in the search-function

### ISSUE THREAD

**Issue by dkehne** [Integreat/app-cross_platform#93]
Special characters not displayed right in the search. In this case a normal "-"-Character is only displayed as its NCR (Numeric character reference,).

![photo_2017-04-04_23-57-32](https://cloud.githubusercontent.com/assets/4182469/24680866/e444a862-1992-11e7-9b58-6e9b4be5b3c3.jpg)

**Comment by BerndNK** [comment]
Thats actually a CMS problem, as the text appears that way in the "excerpt" property of a page.

**Comment by thimmy687** [comment]
is this still open? @svenseeberg @BerndNK
