### ISSUE TITLE
Lehrstellenradar Extra should be triggered with POST

### ISSUE THREAD

**Issue by dkehne** [Integreat/app-cross_platform#96]
The Lehrstellenradar Extra has Inputfields for a Post request. Partnernumber should be hidden and is always 006. Field PLZ  comes from CMS and is also hidden. Field Radius needs to be visible and adjustable. A submit Buttons  fires The Post. So we need a intermediary Page between Extras Page and WebView of Lehrstellenradar. If it's easier and possible to Fire Post without Button, we could also hide the Radius field as well and skip the intermediary Page.

**Comment by thimmy687** [comment]
the plain functionality is now in the branch "Lehrstellenradar", all fields hidden with radius 50km and automatic post request.

still open is to get the plz from the cms (there is a todo label to solve in the extracontentpageviewmodel).

**Comment by thimmy687** [comment]
is done
