### ISSUE TITLE
Pfeil, das es weitere Unterseiten gibt,  fehlt

### ISSUE THREAD

**Issue by FritjofK** [Integreat/app-cross_platform#97]
Beispiel aus LK Heidenheim: 
Berufsausbildung hat noch weitere Unterseiten, enthält aber keinen eigenen Text, sodass kein Pfeil angezeigt wird. 
Unabhängig ob in der zweiten Gliederungsebene auf weitere Seiten oder direkt auf die Seite verlinkt wird, sollte ja keinen Unterschied machen.  Ein Pfeil sollte ja immer da sein. 

![screenshot_2017-04-19-14-51-25](https://cloud.githubusercontent.com/assets/16462172/25183660/821ba582-2518-11e7-826c-8800b3ab1270.png)

**Comment by thimmy687** [comment]
Kann es sein, das die instance CMS seitig nochmal nicht fertig ist?

Ansonsten könntest du das Problem etwas konkretisieren und noch die Unterseiten Posten @FritjofK?

**Comment by FritjofK** [comment]
Hat sich erürbrigt, da zweite und dritte Gliederungsebene zusammen angezeigt werden
